### ISSUE TITLE
Delete Slack Settings feature documentation is missing in Slack integration portion

### ISSUE THREAD

**Issue by mairaayub-6** [CloudplexPlatform/docs#1]
once the slack settings are saved user can also delete those settings by clicking on the red button.
Add this information if necessary .
as shown below, 

![Screenshot_2](https://user-images.githubusercontent.com/67640599/86128458-d1a40880-bafa-11ea-8475-760c1837b95e.png)
![Screenshot_1](https://user-images.githubusercontent.com/67640599/86128473-d668bc80-bafa-11ea-8433-db2b89d26d40.png)

**Comment by jarrarhaider1214** [comment]
Updated @mairaayub-6, please review

**Comment by mairaayub-6** [comment]
yeah fixed. thanks
