### ISSUE TITLE
Tutorials - project - Create Templates - Issues 

### ISSUE THREAD

**Issue by bakhtawermehmood** [CloudplexPlatform/docs#11]
First I assume this is create new kubernetes cluster (user managed) option 
1- you need to update all screenshots in this section as "project" is replaced with "application 
2- mention atleast once "CloudPlex has provided default configuration for network and cluster" but user can add more subnets and sg by following steps. which you mentioned in doc. 
3- we are not providing option to save network and cluster template for now. 
4- there is a tab in between cluster and app, "Kuberenetes cluster" which is missing in doc   
5- mesh is replaced with "app"

**Comment by jarrarhaider1214** [comment]
updated
