### ISSUE TITLE
provider managed - Existing Kubernetes Cluster

### ISSUE THREAD

**Issue by bakhtawermehmood** [CloudplexPlatform/docs#13]
10 and 11 points screenshot are incorrect. they are for new kubernetes cluster 
I have sent you correct screenshot on slack.

**Comment by jarrarhaider1214** [comment]
Point 11 updated, can you please share the screenshot for point 10 as well.

**Comment by bakhtawermehmood** [comment]
sent on slack

**Comment by jarrarhaider1214** [comment]
Updated
