### ISSUE TITLE
user managed - new k8s cluster 

### ISSUE THREAD

**Issue by bakhtawermehmood** [CloudplexPlatform/docs#14]
1- it would be great if we mention "user can download ssh key for future use" 
![image](https://user-images.githubusercontent.com/17968166/86445868-8f620d80-bd2c-11ea-8de0-5ce739358392.png)
![image](https://user-images.githubusercontent.com/17968166/86446108-ea940000-bd2c-11ea-90a6-e27c30004709.png)

2- image after 8th point is not loading 
![image](https://user-images.githubusercontent.com/17968166/86446317-3ba3f400-bd2d-11ea-822b-b501cf344a32.png)

**Comment by jarrarhaider1214** [comment]
fixed and updated.
