### ISSUE TITLE
improvements in getting started page 

### ISSUE THREAD

**Issue by bakhtawermehmood** [CloudplexPlatform/docs#16]
1- replace "project" with application in 3rd point
![image](https://user-images.githubusercontent.com/17968166/86446929-08ae3000-bd2e-11ea-9ae0-0fbbad0b4494.png)

2- registration page with resend activation email functionality is missing. it is for users who have not received activation link in the first attempt, they can resend it. 
![image](https://user-images.githubusercontent.com/17968166/86447328-a144b000-bd2e-11ea-9064-2a6b80b7bce9.png)

**Comment by jarrarhaider1214** [comment]
Updated
