### ISSUE TITLE
Term Application need to follow for synchronization

### ISSUE THREAD

**Issue by Mahwish-khan** [CloudplexPlatform/docs#17]
I think we should use the same terminologies in documentation as well better understanding of platform. 
At some places we are calling project or solution or application. 

It will be better if we stick to one like application 
![2020-07-03_13-07-28](https://user-images.githubusercontent.com/67780496/86447409-c0dbd880-bd2e-11ea-840b-e8175d6ce8f7.png)

**Comment by jarrarhaider1214** [comment]
Updated.
