### ISSUE TITLE
cluster - AWS 

### ISSUE THREAD

**Issue by bakhtawermehmood** [CloudplexPlatform/docs#19]
down arrow button is to fetch **root volume** of image which is provided in "AMI field"

![image](https://user-images.githubusercontent.com/17968166/86448555-588df680-bd30-11ea-96a8-4a301dba3e63.png)

![image](https://user-images.githubusercontent.com/17968166/86448740-9f7bec00-bd30-11ea-802a-61b7624c8e6b.png)

**Comment by jarrarhaider1214** [comment]
Updated
