### ISSUE TITLE
Screenshots are not referring to correct bullet points 

### ISSUE THREAD

**Issue by Mahwish-khan** [CloudplexPlatform/docs#20]
its better to highlight tab about which you are talking in screenshot that will give a better idea and bring user on the same page
![2020-07-03_13-25-25](https://user-images.githubusercontent.com/67780496/86449414-9b040300-bd31-11ea-88e7-15badba37428.png)

**Comment by jarrarhaider1214** [comment]
@Mahwish-khan screenshots are followed by the content, so for this sceenshot the gateway is highlighted in the image above.
