### ISSUE TITLE
cluster - Azure 

### ISSUE THREAD

**Issue by bakhtawermehmood** [CloudplexPlatform/docs#21]
1- we have not mentioned in all clusters doc that user can clone the node pool or add a new one. nodepools added after master will behave like a slave/worker. 
2- default configuration is given for master node pool in our platform 
3- user can use existing storage account or create a new one 
![image](https://user-images.githubusercontent.com/17968166/86449662-ecac8d80-bd31-11ea-9357-2f27ecf41157.png)

**Comment by jarrarhaider1214** [comment]
updated, @bakhtawermehmood please review.

**Comment by bakhtawermehmood** [comment]
yes, it is fine now
