### ISSUE TITLE
page not found on the provided link btn : Provider Managed - New Kubernetes Cluster

### ISSUE THREAD

**Issue by saadmansoorcp** [CloudplexPlatform/docs#25]
![image](https://user-images.githubusercontent.com/67783040/86460471-e0303100-bd41-11ea-8333-536e42f5f299.png)
![image](https://user-images.githubusercontent.com/67783040/86460475-e32b2180-bd41-11ea-8af0-458dda390b31.png)

**Comment by jarrarhaider1214** [comment]
Fixed
