### ISSUE TITLE
manage services- for all manage services:  text and screenshot to be changes

### ISSUE THREAD

**Issue by saadmansoorcp** [CloudplexPlatform/docs#27]
![image](https://user-images.githubusercontent.com/67783040/86462395-fe4b6080-bd44-11ea-9a22-cf5fc66b1c6c.png)

add parameter: click on dynamic parameter to add new parameter. 

p.s: because manage services is only used as a dynamic variables.

and kindly use updated screeshot

**Comment by jarrarhaider1214** [comment]
![image](https://user-images.githubusercontent.com/67363734/86541710-6e660c00-bf28-11ea-8e0d-2a60c50d50f7.png)
I am using app.cloudplex and it screenshot looks updated to me. Can you please share the updated screenshot if any? 

Also can you please provide more details on suggestions. I am still seeing that button of Add Parameters using which user can add static parameter. So although these services will always be used as dynamic variables but still if there is a button to add static variable we cant mention it as dynamic or can we?

**Comment by saadmansoorcp** [comment]
![image](https://user-images.githubusercontent.com/67783040/86587668-7dd66b00-bfa3-11ea-9dd2-9e5b9a08451c.png)

**Comment by jarrarhaider1214** [comment]
Updated
