### ISSUE TITLE
k8s resource - containers

### ISSUE THREAD

**Issue by bakhtawermehmood** [CloudplexPlatform/docs#29]
![image](https://user-images.githubusercontent.com/17968166/86466782-b5e47080-bd4d-11ea-8063-bb7c2140418d.png)

1- container volume section is updated, 
![image](https://user-images.githubusercontent.com/17968166/86466861-dd3b3d80-bd4d-11ea-94d5-50c6bb6f6b9d.png)

2- add volume - there is no link attached with "click here" 

![image](https://user-images.githubusercontent.com/17968166/86468166-4623b500-bd50-11ea-8f1a-61baa9014856.png)

3- 
![image](https://user-images.githubusercontent.com/17968166/86468195-563b9480-bd50-11ea-928f-fe7080cf6cb5.png)

**Comment by jarrarhaider1214** [comment]
updated
