### ISSUE TITLE
manage services: side panel (drop down only available for AZURE )

### ISSUE THREAD

**Issue by saadmansoorcp** [CloudplexPlatform/docs#32]
kindly add drop down for all the clouds in manage services section.
![image](https://user-images.githubusercontent.com/67783040/86470739-7caffe80-bd55-11ea-96ae-5429fa7a3c5d.png)

**Comment by jarrarhaider1214** [comment]
![image](https://user-images.githubusercontent.com/67363734/86539500-381f9100-bf16-11ea-926f-76fc55f5fb9d.png)
Drop-down working for all cloud, try refreshing the page.
