### ISSUE TITLE
Suggestion to Capitalized the Settings when referring to click the tab 

### ISSUE THREAD

**Issue by Mahwish-khan** [CloudplexPlatform/docs#35]
Please see the screenshot below
![2020-07-03_18-11-02](https://user-images.githubusercontent.com/67780496/86472639-e8e03180-bd58-11ea-9168-8986bdf2dcac.png)

**Comment by jarrarhaider1214** [comment]
To make the settings or clickable fields stand out from the rest we are already mentioning those in Bold font. 

I think bold is fine, because ALL CAPS disturb the symmetry of whole content.
