### ISSUE TITLE
ci/cd improvements

### ISSUE THREAD

**Issue by mairaayub-6** [CloudplexPlatform/docs#36]
1) There is only one toggle button of Enable ci/cd
2) once enabled and clicked on configure pipeline you'll see the pipeline type drodown
3) there are three type simple , canary and bluegreen . 
4) Add the details of these types
![Screenshot_4](https://user-images.githubusercontent.com/67640599/86494067-47bf9e00-bd8d-11ea-99d2-2f8c606444a1.png)
![Screenshot_5](https://user-images.githubusercontent.com/67640599/86494087-527a3300-bd8d-11ea-9072-dc47a427cdc1.png)

**Comment by jarrarhaider1214** [comment]
Canary Document updated. 

Will update simple and blue green after discussion with team.

**Comment by jarrarhaider1214** [comment]
done, please review
