### ISSUE TITLE
Broken link in managed clusters protion

### ISSUE THREAD

**Issue by mairaayub-6** [CloudplexPlatform/docs#37]
![Screenshot_6](https://user-images.githubusercontent.com/67640599/86494962-c23ded00-bd90-11ea-8e2c-d133edb2f0e4.png)
![Screenshot_7](https://user-images.githubusercontent.com/67640599/86494966-c407b080-bd90-11ea-8799-c73a33eef995.png)

**Comment by jarrarhaider1214** [comment]
Updated
