### ISSUE TITLE
Canary Release Deployment

### ISSUE THREAD

**Issue by alitjanjua-tech** [CloudplexPlatform/docs#43]
![Screenshot from 2020-07-06 09-00-46](https://user-images.githubusercontent.com/60464160/86554720-d7b93f80-bf67-11ea-8cf8-6ec868e3e755.png)

In this picture paragraph no.4 it says ` keep changes away from customers until the new build has proven to work reliably and correctly in the production environment`
but I think the correct scenario is to keep the changes away from production until the build proves itself to work reliably and correctly on staging environment before applying it to production environment.

**Comment by jarrarhaider1214** [comment]
Updated
