### ISSUE TITLE
Scaling description is ambiguous 

### ISSUE THREAD

**Issue by sadafkhan13** [CloudplexPlatform/docs#44]
![Capture](https://user-images.githubusercontent.com/67887656/86554862-354d8c00-bf68-11ea-912c-5714432f3e0d.PNG)

Change the word **threshold** in last line with **threshold of chosen metric**. 
Also explain range of replicas (min and max) in bullet points like metrics and resources.

**Comment by jarrarhaider1214** [comment]
Updated
