### ISSUE TITLE
Dashboard and Telemetry are discussing the same thing

### ISSUE THREAD

**Issue by junaidk** [CloudplexPlatform/docs#48]
Both Dashboard and Telemetry are discussing the same thing.
We can merge both in a single title `Telemetry`.
Also there is no clear mention of where telemetry components are located i.e How one can navigate to this section and at what time this is available.

**Comment by jarrarhaider1214** [comment]
Removed Dashboard for now, as that was redundant. 

Updated to show from where the monitoring can be accessed.

**Comment by jarrarhaider1214** [comment]
In case of any update, please feel free to reopen to the issue.
