### ISSUE TITLE
Getting Started Sidebar Component

### ISSUE THREAD

**Issue by junaidk** [CloudplexPlatform/docs#54]
Add links of getting started guides in side bar under `Getting Started`.

- Provider Managed - New Kubernetes Cluster
- Provider Managed - Existing Kubernetes Cluster
- User Managed - New Kubernetes Cluster
- User Managed - New On-Premise Kubernetes Cluster

![Screenshot from 2020-07-07 17-48-47](https://user-images.githubusercontent.com/1422281/86783811-353db100-c07a-11ea-8e2f-259af221a4eb.png)

**Comment by jarrarhaider1214** [comment]
Updated
