### ISSUE TITLE
provider managed - new k8s cluster 

### ISSUE THREAD

**Issue by bakhtawermehmood** [CloudplexPlatform/docs#57]
4th point configure cluster 
To configure advanced settings for Cluster, Node Pools and Network click here.

"click here" is not clickable 
![image](https://user-images.githubusercontent.com/17968166/87046739-fb53e280-c212-11ea-93ec-4ca50b8006f8.png)

**Comment by jarrarhaider1214** [comment]
Updated, please review @bakhtawermehmood
