### ISSUE TITLE
Redundant Explaination For Node Scaling

### ISSUE THREAD

**Issue by sadafkhan13** [CloudplexPlatform/docs#61]
![1](https://user-images.githubusercontent.com/67887656/87118911-0734b880-c296-11ea-8262-fca4436372b7.PNG)

![2](https://user-images.githubusercontent.com/67887656/87118916-0bf96c80-c296-11ea-871b-114a6f8176a5.PNG)

This text should be present one time after Node Scaling irrespective of cluster type.

**Comment by jarrarhaider1214** [comment]
Updated, please review @sadafkhan13
