### ISSUE TITLE
Incorrect Placement

### ISSUE THREAD

**Issue by sadafkhan13** [CloudplexPlatform/docs#62]
![00](https://user-images.githubusercontent.com/67887656/87119685-19175b00-c298-11ea-9289-08a967774ae3.PNG)

The highlighted line is incorrect. Metric is a technical term that we can't use for range's attributes. You can write something like 
**User needs to provide min and max  value for number of replicas**. 
and move the red marked section from top to below threshold section.

**Comment by jarrarhaider1214** [comment]
Updated, please review @sadafkhan13
