### ISSUE TITLE
remove the Active Directory from documentation 

### ISSUE THREAD

**Issue by bakhtawermehmood** [CloudplexPlatform/docs#73]
![image](https://user-images.githubusercontent.com/17968166/96085908-eefab800-0eda-11eb-85d2-6f2fa7de5a03.png)
we have hide the active directory part from platform, please remove it from documentation as well.

**Comment by bakhtawermehmood** [comment]
![Uploading image.png…]()

**Comment by bakhtawermehmood** [comment]
![image](https://user-images.githubusercontent.com/17968166/96087448-4b5ed700-0edd-11eb-89e6-1b5e628bdba8.png)

**Comment by jarrarhaider1214** [comment]
fixed
