### ISSUE TITLE
Invited user - changes required in doc

### ISSUE THREAD

**Issue by bakhtawermehmood** [CloudplexPlatform/docs#74]
![image](https://user-images.githubusercontent.com/17968166/96087660-a395d900-0edd-11eb-8966-ad7c3ee35932.png)

incase you need screenshot. 

![image](https://user-images.githubusercontent.com/17968166/96087590-85c87400-0edd-11eb-822a-81db40a88ff4.png)

**Comment by jarrarhaider1214** [comment]
fixed
