### ISSUE TITLE
access management - roles 

### ISSUE THREAD

**Issue by bakhtawermehmood** [CloudplexPlatform/docs#75]
![image](https://user-images.githubusercontent.com/17968166/96087997-333b8780-0ede-11eb-95ae-739d87ec1b82.png)

You can use the below screenshot 
![image](https://user-images.githubusercontent.com/17968166/96088171-77c72300-0ede-11eb-93b8-35613eda23ba.png)

**Comment by jarrarhaider1214** [comment]
fixed
